# Generated by Django 3.0.4 on 2020-12-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20201222_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_courses',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.Course'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=150),
        ),
    ]
