# Generated by Django 3.0.4 on 2020-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20201222_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_course_id',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_parent',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_courses',
            field=models.ManyToManyField(to='meals.Course'),
        ),
    ]
